CONTRIBUTING.md
Fix table of "Running integration tests"
Replace "rackspace/gophercloud" with "php-opencloud/openstack"
=> Fix errors in CONTRIBUTING

composer.lock, samples/networking/v2/create_network.php, samples/networking/v2/create_networks.php, samples/networking/v2/delete_network.php, samples/networking/v2/get_network.php, samples/networking/v2/update_network.php, src/Networking/v2/Api.php, src/Networking/v2/Models/Network.php, src/Networking/v2/Service.php, src/OpenStack.php, tests/integration/Networking/v2Test.php, tests/script/networking_v2, tests/unit/Networking/v2/Fixtures/network-get.resp, tests/unit/Networking/v2/Fixtures/network-post.resp, tests/unit/Networking/v2/Fixtures/network-put.resp, tests/unit/Networking/v2/Fixtures/networks-post.resp, tests/unit/Networking/v2/Models/NetworkTest.php, tests/unit/Networking/v2/ServiceTest.php, tests/unit/OpenStackTest.php
Manage *Network* of the *Networking* service.
Todo :
=> Add "Networking" service

src/Common/Service/Builder.php
I need to pass $options to httpClient() to get debug in identiyService.
=> Pass options to the httpclient of IdentityService

src/Common/Resource/AbstractResource.php
**populateFromReponse** now check the content-type for *application/json* but on some responses the content-type is *application/json; charset=UTF-8*
=> Fix error in populateFromResponse

src/Common/Service/Builder.php
User can now set his own logger
=> Use logger from option

src/Common/Api/QuerySerializer.php
=> Fix QuerySerializer : use getName instead of $paramName

tests/integration/TestCase.php
Add Integration test support for the V2 Identity API services, based on the value of OS_IDENTITY_API_VERSION environment variable.
=> Guzzle 6 fix integration tests for v2 Identity

src/Compute/v2/Api.php, src/Compute/v2/Params.php
Add keyName as an option to specify a key pair to be injected into a server upon creation.
=> Add keyName as an option when creating servers

src/Networking/v2/Api.php, src/Networking/v2/Params.php
@jamiehannaford  Hey what do you think about this?
=> Allow to filter networks by query params

src/Networking/v2/Api.php, src/Networking/v2/Extensions/Layer3/Api.php, src/Networking/v2/Extensions/Layer3/Service.php
=> [rfr] Allows to filter routers and subnets by name and tenant

tests/unit/OpenStackTest.php
=> [rfr] Improve unit test coverage

samples/compute/v2/servers/start_server.php, samples/compute/v2/servers/stop_server.php, src/Compute/v2/Api.php, src/Compute/v2/Models/Server.php, tests/integration/Compute/v2/CoreTest.php, tests/integration/TestCase.php, tests/integration/run.php, tests/unit/Compute/v2/Models/ServerTest.php
This PR will try to cover all server action available in the API. 
Ref: http://developer.openstack.org/api-ref-compute-v2.1.html#os-server-actions-v2.1
Unit tests and functional tests are required.
=> [rfr] Server action

samples/compute/v2/servers/get_server_rdp_console.php, samples/compute/v2/servers/get_server_serial_console.php, samples/compute/v2/servers/get_server_spice_console.php, samples/compute/v2/servers/get_server_vnc_console.php, src/Compute/v2/Api.php, src/Compute/v2/Enum.php, src/Compute/v2/Models/Server.php, src/Compute/v2/Params.php, tests/integration/Compute/v2/CoreTest.php, tests/unit/Compute/v2/Fixtures/server-get-console-rdp.resp, tests/unit/Compute/v2/Fixtures/server-get-console-serial.resp, tests/unit/Compute/v2/Fixtures/server-get-console-spice.resp, tests/unit/Compute/v2/Fixtures/server-get-console-vnc.resp, tests/unit/Compute/v2/Models/ServerTest.php
=> [rfr] Get console vnc/serial/rdp/spice methods

README.md
I have created a slack channel to better receiving feedback as well as support SDK users.
=> Promote Slack channel

composer.json
successfully ran phpunit tests, 
but I couldn't run integration tests, maybe my openstack env variables were wrong.
=> json-schema to v3

src/Identity/v3/Api.php, src/Identity/v3/Models/Policy.php, tests/unit/Identity/v3/Models/PolicyTest.php, tests/unit/Identity/v3/ServiceTest.php
Request JSON body:
`{
"policy": {
"type": "application/json",
"blob": "{'foobar_user': 'role:compute-user'}"
}
}`
=> Add support for creating policies

src/Identity/v3/Api.php, src/Identity/v3/Models/Endpoint.php
You need this in order to can retrieve a specific endpoint.
=> Endpoint model implements Retrievable interface

tests/unit/BlockStorage/v2/Fixtures/GET_quota_set.resp, tests/unit/BlockStorage/v2/Models/QuotaSetTest.php, tests/unit/BlockStorage/v2/ServiceTest.php, tests/unit/Compute/v2/Models/ServerTest.php, tests/unit/Compute/v2/ServiceTest.php
=> [rtr] Bump up unit tests code coverage

src/Compute/v2/Models/Keypair.php, src/Compute/v2/Params.php
Fixes https://github.com/php-opencloud/openstack/issues/122
=> Allow for public keys to be generated by OS, and private key returned

samples/compute/v2/servers/create_interface_attachment.php, samples/compute/v2/servers/delete_interface_attachment.php, samples/compute/v2/servers/get_interface_attachment.php, src/Compute/v2/Api.php, src/Compute/v2/Models/Server.php, src/Compute/v2/Params.php, src/Networking/v2/Models/InterfaceAttachment.php, tests/integration/Compute/v2/CoreTest.php, tests/unit/Compute/v2/Fixtures/server-interface-attachment-get.resp, tests/unit/Compute/v2/Fixtures/server-interface-attachments-post.resp, tests/unit/Compute/v2/Models/ServerTest.php
This PR adds three new `Server` methods to:
* Create/attach interfaces
* Detach interfaces
* Get a single interface
=> Server interface attachments

src/Compute/v2/Models/Fault.php, src/Compute/v2/Models/Server.php
This PR adds a fault property to the `Server` model for asynchronous errors.
=> Add fault property to Server

src/BlockStorage/v2/Models/Snapshot.php, src/BlockStorage/v2/Models/Volume.php, src/Common/JsonSchema/Schema.php, src/Common/Resource/AbstractResource.php, src/Common/Resource/Alias.php, src/Compute/v2/Models/Image.php, src/Compute/v2/Models/Keypair.php, src/Compute/v2/Models/Server.php, src/Identity/v2/Models/Catalog.php, src/Identity/v2/Models/Entry.php, src/Identity/v2/Models/Token.php, src/Identity/v3/Models/Assignment.php, src/Identity/v3/Models/Catalog.php, src/Identity/v3/Models/Service.php, src/Identity/v3/Models/Token.php, src/Images/v2/Models/Image.php, src/Images/v2/Models/Member.php, src/Metric/v1/Gnocchi/Models/Metric.php, src/Networking/v2/Extensions/Layer3/Models/GatewayInfo.php, src/Networking/v2/Extensions/Layer3/Models/Router.php, src/Networking/v2/Extensions/SecurityGroups/Models/SecurityGroup.php, src/Networking/v2/Models/InterfaceAttachment.php, src/Networking/v2/Models/LoadBalancer.php, src/Networking/v2/Models/LoadBalancerHealthMonitor.php, src/Networking/v2/Models/LoadBalancerListener.php, src/Networking/v2/Models/LoadBalancerPool.php, src/Networking/v2/Models/LoadBalancerStatus.php, tests/unit/Common/Resource/AbstractResourceTest.php, tests/unit/Networking/v2/Models/LoadBalancerStatusTest.php, tests/unit/Networking/v2/Models/LoadBalancerTest.php
=> Removed usage of docblocks, fixed several parsing issues

samples/compute/v2/servers/rescue_server.php, samples/compute/v2/servers/unrescue_server.php, src/Compute/v2/Api.php, src/Compute/v2/Models/Server.php, src/Compute/v2/Params.php, tests/integration/Compute/v2/CoreTest.php, tests/unit/Compute/v2/Fixtures/server-rescue.resp, tests/unit/Compute/v2/Fixtures/server-unrescue.resp, tests/unit/Compute/v2/Models/ServerTest.php
This PR adds server rescue and unrescue methods to `Server`.
=> Add server rescue and unrescue

composer.json
This PR upgrade justinrainbow/json-schema to the latest version
=> Upgrade justinrainbow/json-schema

src/Compute/v2/Models/Server.php
This PR adds te SSH keypair name to the `Server` model.
=> Add SSH keypair name to server

src/ObjectStore/v1/Models/Container.php, src/ObjectStore/v1/Models/Object.php
```
#	src/ObjectStore/v1/Models/Container.php
```
=> [2.0.x] Fixed containerName was not set

src/ObjectStore/v1/Models/StorageObject.php
This properties have wrong types in PHPDoc
=> Fixed ObjectStorage PHPDoc of contentLength and lastModified

.github/workflows/unit_tests.yml, src/ObjectStore/v1/Models/Container.php
fixes https://github.com/php-opencloud/openstack/issues/359
=> change \GuzzleHttp\Promise\all to \GuzzleHttp\Promise\Utils::all

.readthedocs.yaml, doc/.gitignore, doc/_exts/samples.py, doc/requirements.txt, doc/services/identity/v3/credentials.rst, doc/services/identity/v3/domains.rst, doc/services/identity/v3/endpoints.rst, doc/services/identity/v3/groups.rst, doc/services/identity/v3/projects.rst, doc/services/identity/v3/roles.rst, doc/services/identity/v3/services.rst, doc/services/identity/v3/tokens.rst, doc/services/identity/v3/users.rst, doc/services/object-store/v1/account.rst, doc/services/object-store/v1/containers.rst, doc/services/object-store/v1/objects.rst
Add readthedocs.yml manifest. Fix python errors.
=> Restore read the docs

.github/workflows/integration_tests.yml, .github/workflows/unit_tests.yml, doc/services/identity/v3/application-credentials.rst, doc/services/identity/v3/index.rst, doc/services/identity/v3/tokens.rst, samples/Identity/v3/application_credentials/add_application_credential.php, samples/Identity/v3/application_credentials/delete_application_credential.php, samples/Identity/v3/application_credentials/show_application_credential.php, samples/Identity/v3/tokens/generate_token_with_application_credential_id.php, samples/Identity/v3/tokens/generate_token_with_username.php, src/Identity/v3/Api.php, src/Identity/v3/Models/ApplicationCredential.php, src/Identity/v3/Models/Credential.php, src/Identity/v3/Models/Token.php, src/Identity/v3/Models/User.php, src/Identity/v3/Params.php, src/ObjectStore/v1/Models/Container.php, src/ObjectStore/v1/Models/StorageObject.php, tests/integration/Identity/v3/ApplicationCredentialsTest.php, tests/integration/Identity/v3/CoreTest.php, tests/unit/Identity/v3/Fixtures/application_credential.resp, tests/unit/Identity/v3/Models/ApplicationCredentialTest.php, tests/unit/Identity/v3/Models/UserTest.php
- add endpoints to create/get/remove application credentials
- add token creation using application credentials
=> Application credentials

doc/services/identity/v3/application-credentials.rst
=> fix doc for application credentials

src/Common/Service/Builder.php, src/Common/Transport/HandlerStackFactory.php, src/OpenStack.php, tests/unit/Common/Transport/HandlerStackTest.php
cherry picked from https://github.com/php-opencloud/openstack/pull/343
=> Handler stack factory

LICENSE
=> fix license: add full text, remove rackspace

tests/sample/Compute/v2/ServerTest.php
default 60 second timeouts might not enough sometimes
=> added bigger timeouts in tests

doc/services/compute/v2/servers.rst
=> fix resume/suspend doc

doc/services/compute/v2/volume-attachments.rst
=> fix doc links

src/Common/Error/Builder.php, tests/sample/Compute/v2/ServerTest.php, tests/unit/Common/Error/BuilderTest.php
- output only body with json
- limit body size to 5000 bytes
fixes #403 
supersedes #404
=> enchance error builder

.github/workflows/integration_tests.yml, COVERAGE.md
- zed moved to unmaintained
- added caracal and dalmatian
=> new openstack versions
