php-opencloud/openstack

- README.md
- composer.json
The composer.json require php 5.6 so I updated the README
> Sync README and composer.json

- src/Common/Service/Builder.php
- src/Identity/v3/Models/Service.php
If Identity service is created in setupHttpClient of the builder, set catalogName and catalogType to false as is done in [OpenStack](https://github.com/php-opencloud/openstack/blob/master/src/OpenStack.php#L72).
The method getUrl of Service, check name only is name is set in the Service. In the OpenStack doc, **name** is marked as optional.
> Fix auth with Identity v3

- src/Identity/v3/Models/Service.php
I'm execute integration tests against Runabove and in some cases the region of endpoints is empty.
In the OpenStack documentation, region is marked as Optional.
> Endpoint of Service with empty region

- src/Common/Service/Builder.php
- src/Common/Transport/Utils.php
Refactor private method Builder.normalizeUrl into OpenStack\Common\Transport\Utils as a public static function. This change makes the normalizeUrl callable from external methdos too.
> Refactor normalizeUrl

- tests/integration/Runner.php
The class name of integration test was not properly converted in case
of object store. The service names were collected from samples directory
where object store was represented as "object_store" meanwhile the
integration test name is called "ObjectStore" in camel-case format.
This fix adds a new camel case formatter that properly converts the
object_store to ObjectStore.
> Fix class name of specific integration tests

- tests/integration/Compute/v2Test.php
- tests/integration/Identity/V3Test.php
- tests/integration/ObjectStore/V1Test.php
- tests/integration/TestCase.php
- tests/integration/Utils.php
Move the integration TestCase auth classes into OpenStack\Integration\Utils. Rewrite the connection substitution code of TestCase.sampleFile to provide v2 auth compatibility for sample classes. Also fix the affected integration tests using the getAuthOpts calls.
> Refactor integration test auth to support v2 identity

- tests/integration/ObjectStore/V1Test.php
The StreamInterface was changed in Guzzle6 and now it is using Psr\Http\Message\StreamInterface. The object download test now checks the result against this new interface instead of GuzzleHttp\Stream\StreamInterface.
> Fix the object download integration test

- tests/integration/ObjectStore/V1Test.php
Container delete test failed because the container was not empty. This fix also delete the object created by the copy object step.
> Fix object store integration test

- README.md
added docs for php-opencloud/openstack, previously only the official docs were linked.
> add docs for php-opencloud/openstack

- src/Identity/v2/Models/Entry.php
The changeset 099ae8b210b3feaa2a1c259f336ac800a6ab9558 broke the v2 identity api, and caused a private property access issue on v2's Entry class. This patchset makes the private properties to
public to make it accessible from AbstractResource.populateFromArray() method.
> Fix v2 identity private property access bug

- src/Common/Transport/Utils.php
As per the changelog entry at
https://github.com/php/php-src/commit/9d037d574cc359405c7a818c2235644633705999,
PHP7 treats empty-string equivalents as syntax error, as they are not
valid JSON. Special-case this in the json_decode path.
Signed-off-by: Nishanth Aravamudan <nish.aravamudan@canonical.com>
> Common/Transport/Utils.php: PHP7 JSON treats empty strings as syntax error

- .travis.yml
This will bring build time from 2m58s to 1m37s. @jamiehannaford
> [rfr] Build optimization: Disable xdebug in .travis.yml

- composer.json
- src/OpenStack.php
```php
$requestOptions = [
'verify' => false,
'headers' => ['User-Agent' => 'PHP-OPENCLOUD/SDKv1.0']
];
$params = [
'authUrl' => 'http://172.16.113.139:5000/v3',
'region'  => 'RegionOne',
'user'    =>
array(
'name' => 'admin',
'password' => '034cdbdb0fd84c5f',
'domain'   =>
array(
'id' => 'default',
),
),
'requestOptions' => $requestOptions
];
$openstack = new OpenStack\OpenStack($params);
```
> [wip] Guzzle request options

- src/ObjectStore/v1/Models/Object.php
Since a `download` also provides the `contentLength`, `hash`, `lastModified` etc. We should populate in order to prevent the requirement to execute multiple http requests while one is enough.
> Also populate response from download

- doc/index.rst
There are some very clear PHP 7 dependencies now; just bumping the documentation to reflect this.
> Update PHP requirement

- src/Identity/v3/Api.php
- tests/integration/Identity/v3/CoreTest.php
- tests/unit/Identity/v3/Fixtures/service.resp
- tests/unit/Identity/v3/ServiceTest.php
You cannot set `description` for a new service right now, I see the patchService() method have it, so I added it also for the creation.
> Allow postService() method to set description property

- src/ObjectStore/v1/Models/Object.php
This PR fixes inconsistent behaviour when downloading a file with MIME type of `application/json` using `ObjectStoreV1` service.
`$object->download()` now properly returns Stream with pointer sets at position 0.
> [rfr] Fixed stream pointer pointing to end of stream

- src/ObjectStore/v1/Models/Object.php
This PR allows download options.
echo $obj->download()->getContents(); 
echo $obj->download(['range' => 'bytes=0-20', 'ifModifiedSince' => 'Mon, 17 Jul 2017 07:28:00 ICT'])->getContents();
> [rfr] Add swift download options

- src/Compute/v2/Models/Server.php
This PR adds the power state and the vm state of a server to the server model. Both are present in the API response (https://developer.openstack.org/api-ref/compute/#show-server-details) but currently not represented in the model.
> Add power state and vm state to server model

- src/Compute/v2/Service.php
`getAvailabiltyZones` -> `getAvailabilityZones`
> Fix typo breaking doc generation

- src/Common/JsonSchema/Schema.php
Hi @jamiehannaford 
The PR removes changes made in the very first implementation of #159 (raw arrays) that are left in the code.
> Simplified an expression for alias resolution

- src/OpenStack.php
This PR enables debug messages in Guzzle for the first request to Identity Service.
> Enabled debug messages for authentication request

- src/Common/Service/Builder.php
- src/Compute/v2/Api.php
- src/Compute/v2/Models/Keypair.php
- src/Compute/v2/Params.php
- src/OpenStack.php
- tests/unit/Common/Service/BuilderTest.php
- tests/unit/Compute/v2/Fixtures/keypair-get.resp
- tests/unit/Compute/v2/Models/KeypairTest.php
By default, for backward compatibility, OpenStack API chooses the minimum supported version.
This also means certain features won't be available until a specified version is set in API calls via header, e.g `OpenStack-API-Version: compute 2.17`;
This PR allows SDK users to specify micro-version of a given service.
Usage: 
```php
$compute = $openstack->computeV2(['microVersion' => '2.27']);
```
> Specify service micro version

- doc/services/identity/v3/projects.rst
The document references to wrong example file on grantGroupRole of Identity/v3/Project service.
> Fix wrong example code of grandGroupRole in Identity/v3/Project

- doc/services/identity/v3/tokens.rst
- samples/identity/v3/tokens/export_authentication_token.php
- samples/identity/v3/tokens/use_cached_authentication_token.php
- src/Identity/v3/Models/Token.php
- src/Identity/v3/Service.php
- src/OpenStack.php
- tests/unit/Identity/v3/ServiceTest.php
Proof-of-concept re-use authentication token
Usage:
Export token
```php
<?php
// Export authentication credential
$params = [];
$openstack = new OpenStack\OpenStack($params);
$token = $openstack->identityV3()->generateToken($params);
// This is an serializable array can be re-use
$cachedToken = $token->export();
// Save token to file
file_put_contents('cache.json', \json_encode($cachedToken));
// Or even better wrt scalability, store token in memcache
$memcache->set('array', $cachedToken, $expiration);
```
Use exported token
```php
// Authenticate using cache credential
$cachedToken = \json_decode(file_get_contents('cache.json'), true);
// params need to have all other mandatory fields such as `authUrl`, `user`, etc..
$params = [
'cachedToken' => $cachedToken
]; 
$openstack = new …
```
> Auth token caching

- src/Identity/v3/Api.php
- tests/unit/Identity/v3/Models/PolicyTest.php
Added missing `jsonKey` key on patchPolicy() method and fixed affected test.
> Fixing Policy PATCH method

- samples/compute/v2/servers/get_server_console_output.php
- src/Compute/v2/Api.php
- src/Compute/v2/Models/Server.php
- src/Compute/v2/Params.php
- tests/integration/Compute/v2/CoreTest.php
- tests/unit/Compute/v2/Fixtures/server-get-console-output.resp
- tests/unit/Compute/v2/Models/ServerTest.php
This PR adds the ability to get the console output of a server (see [OpenStack docs](https://developer.openstack.org/api-ref/compute/#show-console-output-os-getconsoleoutput-action) ).
> Add server console output

- src/ObjectStore/v1/Models/MetadataTrait.php
- tests/unit/ObjectStore/v1/Fixtures/HEAD_Object.resp
- tests/unit/ObjectStore/v1/Models/ObjectTest.php
Hello,
This PR fixes the followiong metadata parsing error :
```php
$mask = 'X-Object-Meta-';
$header = 'X-Object-Meta-Manufacturer';
echo ltrim($header, $mask); // "nufacturer"
```
See live example [here](https://3v4l.org/f9aLm).
Actually, `ltrim` does not replaces by the whole string but uses chars in the given mask instead, and stops when it encounter a char which is not in the mask.
> fix metadata header parsing

- src/Networking/v2/Extensions/Layer3/Api.php
- src/Networking/v2/Extensions/Layer3/Service.php
Adding possibility to get Floating Ips by Tennant Id in the function to list floating ips.
Example : 
$openstack->networkingV2ExtLayer3()
->listFloatingIps(['tenantId' => 'tennantId']);
> Adding possibility to filter floating ips by TennantId

- src/Networking/v2/Extensions/Layer3/Models/FloatingIp.php
- tests/unit/Networking/v2/Extensions/Layer3/Models/FloatingIpTest.php
Fix issue with retrieving FloatingIP data. Previously retrieved only object without populated data.
> Fix issue with retrieving FloatingIP

- src/Networking/v2/Extensions/SecurityGroups/Api.php
Add ability to specify tenant_id when create Security Group Rule. It is useful if requests are made from admin tenant. Instead Security Group Rule is created with callers tenant ID.
> Add tenantId to postSecurityRules api

- doc/services/compute/v2/servers.rst
- samples/compute/v2/servers/reset_server_state.php
- src/Compute/v2/Api.php
- src/Compute/v2/Models/Server.php
- src/Compute/v2/Params.php
Add functionality to reset the state of a VM.
> Add Server::resetState method

- src/ObjectStore/v1/Models/StorageObject.php
When listing objects with `delimiter=/` the response for any sub directory will only contain `{"subdir": "folder/"}`
Without this alias there is no way get a list of sub directories (without listing *all* objects)
> Add 'subdir' as alias for 'name' in StorageObject

- src/Common/Resource/AbstractResource.php
The serialize method don't handle correctly `\DateTimeImmutable`
The unserialize method expect a string (\DateTimeImmutable constructor) 
```php
} elseif (strcasecmp($type, '\datetimeimmutable') === 0) {
$val = new \DateTimeImmutable($val);
```
But the serialize method serialize '\DateTimeImmutable' as object 
This throw an `DateTimeImmutable::__construct() expects parameter 1 to be string, object given` on calling `->populateFromArray((array) $serialize) `
> Handle Datetime serialization

- composer.json
- src/BlockStorage/v2/Api.php
- src/BlockStorage/v2/Models/Snapshot.php
- src/BlockStorage/v2/Models/Volume.php
- src/BlockStorage/v2/Params.php
- src/Compute/v2/Api.php
- src/Compute/v2/Models/Keypair.php
- src/Compute/v2/Params.php
- src/Networking/v2/Api.php
- src/Networking/v2/Extensions/Layer3/Models/FixedIp.php
- src/Networking/v2/Extensions/Layer3/Models/FloatingIp.php
- src/Networking/v2/Extensions/Layer3/Models/GatewayInfo.php
- src/Networking/v2/Extensions/SecurityGroups/Api.php
- src/Networking/v2/Extensions/SecurityGroups/Params.php
- src/Networking/v2/Extensions/SecurityGroups/Service.php
- src/Networking/v2/Models/Network.php
- src/Networking/v2/Models/Port.php
- src/Networking/v2/Params.php
- src/ObjectStore/v1/Models/StorageObject.php
- tests/unit/BlockStorage/v2/Models/VolumeTest.php
- tests/unit/Networking/v2/Extensions/Layer3/Fixtures/Router.resp
- tests/unit/Networking/v2/Extensions/Layer3/Models/FloatingIpTest.php
- tests/unit/Networking/v2/Extensions/Layer3/Models/RouterTest.php
- tests/unit/Networking/v2/Fixtures/port_get.resp
- tests/unit/Networking/v2/Models/PortTest.php
Some minor updates I cherry-picked from a project I've been working on.
You have time to do a quick code review @laszlof?
> Minor Updates

- src/ObjectStore/v1/Models/Container.php
- tests/unit/ObjectStore/v1/Models/ContainerTest.php
This fixes an off by one error with the number of segments of large objects uploaded to Swift.
The total number of segments was determined with `round($streamSize/$segmentSize)`. In cases like `$streamSize=24` and `$segmentSize=10` this resulted in one segment too few that was uploaded. This has been fixed by simply omitting `round()`. I also updated the test which did not fail before by pure chance.
> Fix number of segments of a large object

- src/Identity/v3/Models/Endpoint.php
- src/Identity/v3/Models/Service.php
Two of the three suggested changes included.
- Allow wildcard region
- Fix == comparison operator
The third change is unclear if that's a bug or not. Not including.
> Fixes for Issue 287

- doc/services/object-store/v1/objects.rst
- samples/objectstore/v1/objects/download_stream.php
- src/Common/Api/OperatorTrait.php
- src/ObjectStore/v1/Models/StorageObject.php
- tests/integration/ObjectStore/v1/CoreTest.php
- tests/unit/Common/Api/OperatorTraitTest.php
> Allow user to provide Guzzle options in requests

- src/Common/Auth/AuthHandler.php
- tests/unit/Common/Api/OperatorTraitTest.php
- tests/unit/Common/Error/BuilderTest.php
- tests/unit/Common/Resource/AbstractResourceTest.php
- tests/unit/Common/Transport/UtilsTest.php
- tests/unit/ObjectStore/v1/Models/ObjectTest.php
- tests/unit/TestCase.php
I needed to do this change in order to prevent this error `Call to undefined function GuzzleHttp\Psr7\modify_request()`.
This PR removes deprecated calls to guzzle functions.
I checked all the code, and this was the only missing call to `GuzzleHttp\Psr7\` deprecated functions. I updated the unit tests.
> Fix Call to undefined function GuzzleHttp\Psr7\modify_request()

- composer.json
Unlike https://github.com/php-opencloud/openstack/pull/356 this PR allows using uri-template 0.2 for backward compatibility.
> allow uri-template 1.0 to be compatible with the latest Laravel

- .github/workflows/integration_block_storage.yml
- .github/workflows/integration_compute.yml
- .github/workflows/integration_identity.yml
- .github/workflows/integration_images.yml
- .github/workflows/integration_networking.yml
- .github/workflows/integration_object_storage.yml
- .github/workflows/unit_tests.yml
- README.md
- doc/index.rst
- samples/Compute/v2/images/delete_image.php
fixes #351
adds information about php 8.x to docs
add badges and remove old contacts to readme.md
> Fix documentation

- doc/services/block-storage/v2/snapshots.rst
- doc/services/images/v2/images.rst
- samples/BlockStorage/v2/snapshots/list_sorted.php
- samples/Images/v2/images/list_sorted.php
- src/Common/Api/AbstractParams.php
- tests/integration/BlockStorage/v2/CoreTest.php
- tests/integration/Images/v2/CoreTest.php
sortKey and sortDir for BlockStorageV2 and ImagesV2 fixed sentAs and tests
supersede part of https://github.com/php-opencloud/openstack/pull/362
> Pr 362 sortkey sortdir

- src/BlockStorage/v2/Models/Snapshot.php
- src/BlockStorage/v2/Models/Volume.php
- src/BlockStorage/v2/Models/VolumeType.php
- src/BlockStorage/v2/Service.php
- src/Common/Resource/AbstractResource.php
- src/Common/Resource/Creatable.php
- src/Common/Resource/Listable.php
- src/Common/Resource/OperatorResource.php
- src/Common/Resource/ResourceInterface.php
- src/Compute/v2/Models/Keypair.php
- src/Compute/v2/Models/Server.php
- src/Compute/v2/Service.php
- src/Identity/v3/Models/Domain.php
- src/Identity/v3/Models/Group.php
- src/Identity/v3/Models/Project.php
- src/Identity/v3/Models/User.php
- src/Identity/v3/Service.php
- src/Images/v2/Models/Image.php
- src/Images/v2/Models/Member.php
- src/Images/v2/Service.php
- src/Metric/v1/Gnocchi/Models/Resource.php
- src/Metric/v1/Gnocchi/Service.php
- src/Networking/v2/Extensions/Layer3/Models/FloatingIp.php
- src/Networking/v2/Extensions/Layer3/Models/Router.php
- src/Networking/v2/Extensions/Layer3/Service.php
- src/Networking/v2/Extensions/SecurityGroups/Service.php
- src/Networking/v2/Service.php
- src/ObjectStore/v1/Models/Container.php
- src/ObjectStore/v1/Models/StorageObject.php
- src/ObjectStore/v1/Service.php
* `Creatable` interface
* methods which returns `\Generator`
> added phpdocs for better type hinting

- src/Common/Resource/HasWaiterTrait.php
- tests/integration/BlockStorage/v2/CoreTest.php
- tests/integration/BlockStorage/v3/CoreV2Test.php
- tests/integration/Compute/v2/CoreTest.php
- tests/integration/Identity/v3/ApplicationCredentialsTest.php
- tests/integration/Identity/v3/CoreTest.php
- tests/integration/Images/v2/CoreTest.php
- tests/integration/Networking/v2/CoreTest.php
- tests/integration/Networking/v2/Layer3Test.php
- tests/integration/ObjectStore/v1/CoreTest.php
- tests/integration/TestCase.php
use `include_once $this->sampleFile(` instead of `$path = $this->sampleFile(..); include_once $path`
> Refactor tests

- composer.json
- src/Common/Api/Operation.php
- src/Common/Api/OperatorTrait.php
- src/Common/Auth/AuthHandler.php
- src/Common/Service/Builder.php
- src/Identity/v2/Api.php
- src/Identity/v3/Api.php
- src/Identity/v3/Models/Token.php
- tests/sample/Compute/v2/TestCase.php
- tests/sample/ObjectStore/v1/ContainerTest.php
- tests/unit/Common/Api/OperatorTraitTest.php
- tests/unit/Common/Auth/AuthHandlerTest.php
- tests/unit/Identity/v2/ServiceTest.php
- tests/unit/Identity/v3/ServiceTest.php
- tests/unit/TestCase.php
The `AuthHandler` didn't use authorization for POST requests which have `tokens` in uri. This was created to avoid infinite recursion when obtaining a token would require obtaining a token - https://github.com/php-opencloud/openstack/blob/9f817df9407a7f59579f001c00daba0a8f00de59/src/Common/Auth/AuthHandler.php#L65. 
However this emerges another problem: if swift container name has `tokens` in it, the request uri would contain this term. So any POST request would be sent without token. 
This PR removes that check and uses a separate key `skipAuth` in the `Api` classes to mark api requests which must skip token generation.
> Fix container requests with "tokens" in its name

- doc/setup.rst
- src/Common/Auth/IdentityService.php
- src/Common/Error/Builder.php
- src/Common/Service/Builder.php
- src/Common/Transport/HandlerStack.php
- src/Common/Transport/HandlerStackFactory.php
- src/Common/Transport/Middleware.php
- src/Identity/v3/Service.php
- src/OpenStack.php
- tests/sample/Compute/v2/TestCase.php
- tests/sample/Identity/v3/TokenTest.php
- tests/unit/Common/Error/BuilderTest.php
- tests/unit/Identity/v3/ServiceTest.php
Related issues:
https://github.com/php-opencloud/openstack/issues/335
https://github.com/php-opencloud/openstack/issues/398
setting `errorVerbosity` to 0 will not show header and body of request in exception.
> add errorVerbosity

- .github/workflows/integration_tests.yml
- src/ObjectStore/v1/Models/MetadataTrait.php
- tests/unit/ObjectStore/v1/Fixtures/GET_Container.resp
- tests/unit/ObjectStore/v1/Fixtures/GET_Object.resp
- tests/unit/ObjectStore/v1/Fixtures/HEAD_Account.resp
- tests/unit/ObjectStore/v1/Fixtures/HEAD_Container.resp
- tests/unit/ObjectStore/v1/Fixtures/HEAD_Object.resp
- tests/unit/ObjectStore/v1/Models/AccountTest.php
- tests/unit/ObjectStore/v1/Models/ContainerTest.php
- tests/unit/ObjectStore/v1/Models/ObjectTest.php
supersedes https://github.com/php-opencloud/openstack/pull/406
Compares headers case insensitively, but leaves the metadata names original case for backward compatibility.
> make swift metadata header case insensitive 

- tests/sample/Compute/v2/VolumeAttachmentTest.php
This test is failing quit often for the dalmatian version
> increase sleep before testing detach. The VM must be completely up.

- samples/Networking/v2/floatingIPs/create.php
- src/Networking/v2/Extensions/Layer3/Api.php
- src/Networking/v2/Extensions/Layer3/ApiTrait.php
- src/Networking/v2/Extensions/Layer3/Models/FloatingIp.php
- src/Networking/v2/Extensions/Layer3/Params.php
- src/Networking/v2/Extensions/Layer3/ParamsTrait.php
- tests/sample/Networking/v2/FloatingIpTest.php
- tests/unit/Networking/v2/Extensions/Layer3/Fixtures/FloatingIp.resp
- tests/unit/Networking/v2/Extensions/Layer3/Fixtures/FloatingIps.resp
- tests/unit/Networking/v2/Extensions/Layer3/Models/FloatingIpTest.php
The [OpenStack API for Floating IPs](https://docs.openstack.org/api-ref/network/v2/index.html#create-floating-ip) supports:
- an optional `description` of the floating IP
- optionally specifying a specific `subnet_id` upon creation of the floating IP
The subnet ID is not returned on GET.
This is my first time working with php-opencloud/openstack and my first pull request to this project. I have extended the unit tests to verify the description. I did not run the integration tests but verified the changes against our OpenStack environment.
> extend FloatingIP with description and subnet_id

- composer.json
Using composer 2.8.8 , it's not possible to require nimbusoft/flysystem-openstack-swift . That package uses openstack which is limited to justinrainbow/json-schema ^5.2. But composer 2.8.8 requires at least ^6.3  . This MR adds support for installing ^6.0 with openstack.
> nimbusoft/flysystem-openstack-swift can't be installed due to use of json-schema 5
